import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { getBlocks, getSingleBlock } from '../../api/block';
import { client } from '../../api/client';
import { RootState, AppThunk } from '../../app/store';

export interface IBlock {
  hash: string;
  height: number;
  time: number;
  block_index: number;
  miner: string;

}

export interface IExtraData {
  hash: string;
  height: number;
  time: number;
  block_index: number;
  miner: string;
  bits: number;
}

export interface BlocksState {
  loading: boolean;
  status: string;
  blocks: IBlock[];
  extraData: IExtraData[];
}

const initialState: BlocksState = {
  loading: false,
  status: 'idle',
  blocks: [],
  extraData: []
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.



export const blocksSlice = createSlice({
  name: 'blocks',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getBlocks.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getBlocks.fulfilled, (state, action) => {
        state.status = 'idle';
        state.blocks = action.payload;
      })
      .addCase(getSingleBlock.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(getSingleBlock.fulfilled, (state, action) => {
        state.extraData.push(action.payload)
      })
  },
});

// export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const selectCount = (state: RootState) => state.counter.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount: number): AppThunk => (
//   dispatch,
//   getState
// ) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

export default blocksSlice.reducer;
